name: Examples
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        shell: julia --project=docs/ {0}
        run: |
          using Pkg
          Pkg.add([
              PackageSpec(name="PolyJuMP", rev="master"),
              PackageSpec(path=pwd()),
          ])
          Pkg.instantiate()
      - name: Run examples
        run: julia --project=docs --color=yes examples/run_examples.jl
