name: Examples
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        shell: julia --project=docs/ {0}
        run: |
          using Pkg
          Pkg.add([
              PackageSpec(url="https://github.com/blegat/HomotopyContinuation.jl", rev="dynamicpolynomials_v0.6"),
              PackageSpec(name="StarAlgebras", rev="main"),
              PackageSpec(name="SymbolicWedderburn", rev="mk/StarAlgebras_0_3"),
              PackageSpec(name="MultivariateBases", rev="master"),
              PackageSpec(name="SemialgebraicSets", rev="master"),
              PackageSpec(name="MultivariateMoments", rev="master"),
              PackageSpec(name="PolyJuMP", rev="master"),
              PackageSpec(path=pwd()),
          ])
          Pkg.instantiate()
      - name: Run examples
        run: julia --project=docs --color=yes examples/run_examples.jl
